language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install libaudit-dev libssl-dev libslang2-dev python-dev libpython-dev libperl-dev binutils-dev libiberty-dev liblzma-dev bison flex libnuma-dev
  - # Precompiled version of elfutils in newer version (0.170)
  - wget -c "https://swanson.kdab.com/owncloud/index.php/s/RzRwIkFuTKI30t3/download" -O elfutils.tar.bz2
  - sudo tar -xf elfutils.tar.bz2 -C /
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - sudo mv linuxdeployqt*.AppImage /usr/bin/linuxdeployqt
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - chmod a+x upload.sh
  - sudo mv upload.sh /usr/bin/github-upload

script:
  - set -e # Exit immediately if anything fails
  - cd tools/perf
  - make -j$(nproc) prefix=/usr DESTDIR=$PWD/appdir/ install
  - rm appdir/etc/bash_completion.d/perf # ensure this perf script isn't found by linuxdeployqt, note that we cannot bundle it usefully anyways
  - mkdir -p ./appdir/usr/share/applications/ ./appdir/usr/lib/
  - touch appdir/perf.png # TODO: get a proper icon for perf
  - echo -e '[Desktop Entry]\nType=Application\nName=perf\nExec=perf\nIcon=perf\nCategories=Development;\n' > ./appdir/perf.desktop
  - # also include the elfutils backend library ABI specific implementations
  - cp -va /usr/lib/x86_64-linux-gnu/elfutils/* ./appdir/usr/lib/
  - # Actually create the AppImage
  - linuxdeployqt appdir/perf.desktop -bundle-non-qt-libs -no-plugins -appimage
  - # upload the appimage to GitHub
  - mv perf-*.AppImage perf-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - github-upload ./perf-git.*-x86_64.AppImage